### ISSUE TITLE
最终还是没跑起来，反馈几个问题

### ISSUE THREAD

**Issue by otakustay** [shuiqukeyou/E-HentaiCrawler#1]
1. 需要安装的包描述太少了，`pip install requests pymysql bs4`
2. 建表的语句是错的，一堆`verchar`应该是`varchar`
3. config中的`TARGET`里有个字符串没加引号

最后没跑起来的原因是macOS上python3的`qi.qsize()`是不能用的……我只是想做一些数据上的分析，你能不能直接dump一个最新的数据表给我算了，可以的话我单独和你联系……

**Comment by shuiqukeyou** [comment]
@otakustay 已经上传了，请参见说明页面，几个BUG也修了。因为我重构的源码有一堆复制粘贴的老代码，里面有些地方没注意到，重跑的时候也没意识到要重跑建表，TARGET也是直接基于原来的数据库跑的，实际上不是用的这个值，之后改回去的时候忘了加引号。谢谢提醒。

**Comment by otakustay** [comment]
似乎没能在 https://github.com/shuiqukeyou/E-HentaiCrawler/commit/1670e935c3eab10d3f7b641279ab375d8990f7df 这个commit里找到具体数据在哪里，你看是否能把mysql的表整个给dump出来……因为反正macOS的原因我是肯定跑不了这脚本了

**Comment by shuiqukeyou** [comment]
@otakustay README的最底下有个百度云链接嘞，链接: http://pan.baidu.com/s/1boQaILL 密码: 8qsg，字段说明在压缩包里有

**Comment by otakustay** [comment]
非常感谢，数据已收到~
