### ISSUE TITLE
程序运行bug: "IndexError: list index out of range"

### ISSUE THREAD

**Issue by BLMYX01** [shuiqukeyou/E-HentaiCrawler#2]
配置后无法运行源代码，提示如下：
Traceback (most recent call last):
  File "E:/BLMYX/Python/E-HentaiCrawler/Proxy/IPPool.py", line 85, in getip_from_pool
    timeout = 5).json()[0]
IndexError: list index out of range
经过调试，发现是IPPool.py中getip_from_pool()函数返回调用requests函数传入的URL参数有误，删除网址后边多出的空格即可。（楼主大大可以调一下？哇这边初学者研究了好久orz

**Comment by shuiqukeyou** [comment]
那个空格按理来说不会有影响，因为你看88行的请求参数最后也有个空格，事实上这两行URL是在浏览器里调用测试没问题再后复制过来的

你那边可以稳定复现这个BUG吗，比如出现“删了那个空格就能运行，不删就是不能运行”这种情况

.json()这个方法返回的是一个list，只要里面有元素，调用list[0]就不可能出现list index out of range，除非IPProxyPool项目没有爬到任何可用ip，直接返回为空list，这种情况才会出现list index out of range
而且那一段代码有两级except BaseException:，按说是不应该抛出IndexError的，只会打印一个'从IP池获取IP失败，请检查IPProxyPool是否还在运行'，所以你是不是改了源码了？
（现在回头看看我当时用了一堆print而不是log模块简直丢人，不过懒得改了）

另，我这边测试的结果是有没有空格不影响运行
![image](https://user-images.githubusercontent.com/18672635/31262279-830c22ec-aa8c-11e7-8917-a0cfc68a0b07.png)

还有一种可能性就是新的IPProxyPool项目及其依赖项目对URL的参数要求更加严格了（我这里是老版本的），以前可以带空格现在不行了，但是这种可能性很低，因为有的浏览器会自动加空格有的不会自动加，不大可能越改越严格

**Comment by BLMYX01** [comment]
emmmm.... 总之这边的情况是这样子的：将大大您的代码clone回本地之后，我先是在Config.py修改数据库连接以及cookie信息、运行了new_datatable.py。接着就等IPProxyPool项目运行至稳定状态，之后执行程序就出现IndexError: list index out of range，然后程序终止(运行环境为PyCharm)
当初是通过Pycharm的调试功能，发现获取代理的函数始终返回null，命令行运行如下：
![default](https://user-images.githubusercontent.com/19875394/31282685-e5c4ce3a-aae5-11e7-8e4e-787ab8fea898.png)
原因我也orz...不太清楚

**Comment by BLMYX01** [comment]
印象中好像没有修改什么关键代码。
还有一个问题想问一下大大，不知道是代理本身确实有问题还是我哪里有搞错，
第一遍运行的时候是无法爬取任何内容（连接错误），然后就不断删除已经获取的代理，我直接关闭命令行之后，再次运行就这样了：
![2](https://user-images.githubusercontent.com/19875394/31283285-c2bb0f38-aae7-11e7-80f9-2cdf0b125b91.png)
emmm.....然后程序就不会动了（而且持续占用CPU资源），大大当初在爬的时候有遇到过类似错误吗？

**Comment by BLMYX01** [comment]
经过调试，发现html = requests.get('https://exhentai.org/?page=' + str(0), headers=ehheaders, cookies=excookies, proxies = proxy).text 返回的是null，然后程序就卡在那里了。
稍微修改源代码：
proxy = IPPool.getIP() 
format_proxy = {
    'http': 'http://'+str(proxy[0])+':'+str(proxy[1])
}
html = requests.get('https://exhentai.org/?page=' + str(0), headers=ehheaders, cookies=excookies, proxies = format_proxy).text
这样就能够爬取页面信息了！

**Comment by BLMYX01** [comment]
经过调试，发现html = requests.get('https://exhentai.org/?page=' + str(0), headers=ehheaders, cookies=excookies, proxies = proxy).text 返回的是null，然后程序就卡在那里了。
 稍微修改源代码：
proxy = IPPool.getIP()
 format_proxy = {
 'http': 'http://'+str(proxy[0])+':'+str(proxy[1])
 }
 html = requests.get('https://exhentai.org/?page=' + str(0), headers=ehheaders, cookies=excookies, proxies = format_proxy).text
这样就能够让程序顺利运行下去，
不过至于爬取信息.......emmmmmm还是一直提示 API爬虫的代理已被Ban，更换代理，代理服务器不可用或响应时间过长什么的

**Comment by shuiqukeyou** [comment]
我不是什么大手子，写过的稍微大一点的东西就是这个了，所以也不用大大之类的称呼，咸鱼一条

我把最新的IPProxyPool项目clone下来运行了一下，两个BUG都是IPProxyPool项目变化导致的
第一个：（有空格就无法获取到代理）是最新IPProxyPool对参数的检测更加严格了导致的
第二个：（目录发生器挂了）是最新的IPProxyPool加入了一个评分制度导致的，以前的老版IPProxyPool返回的参数直接就是：
[["122.226.189.55", 138], ["183.61.236.54", 3128], ["61.132.241.109", 808], ["183.61.236.53", 3128], ["122.227.246.102", 808]]
其中的每一个是直接可以当作代理参数用的“[IP,端口]”的格式
现在多了个评分：
[["122.226.189.55", 138, 10], ["183.61.236.54", 3128, 10], ["61.132.241.109", 808, 10], ["183.61.236.53", 3128, 10], ["122.227.246.102", 808, 10]]
导致直接往里面传会出错，所以加上一步format_proxy后就可正常执行了。而第一个需要使用代理的就是目录发生器（indexgeter.py）
事实上就算他不出错，后面的API爬虫和页面爬虫也会出错，因为后面我的代理参数也是默认直接用的
由于后面的出错我是拿了一个except BaseException直接拦截所有考虑之外的错误，然后终止这个线程，并把这个线程的工作状态以及当前使用的代理传入到错误处理队列中，由错误处理进程去进行处理。
错误处理进程会测试那个代理看是否可用，可用就把代理和任务塞回代理队列和任务队列，不可用就由错误处理进程把这个任务处理掉并且删除这个代理
但是，由于IPProxyPool项目的变化，导致爬虫会出错，被except BaseException捕捉到后进入错误处理，错误处理测试这个代理当然还是不可用，于是就删除IP，于是你就看到了丧心病狂的不断删除已获取的代理
至于为什么目录发生器挂了之后程序还继续占CPU，是因为这是个生产者消费者模型，目录发生器挂了后仍然会有一大堆爬虫进程等待目录发生器给它们地址，错误处理进程也会活着，会持续消耗资源
没写目录发生器的错误处理是因为这个项目鲁棒性不好，事实也证明了这个，我期望的是：如果出现什么错误，整个代码就会直接停下来，如果把目录发生器的错误处理也写了，你就只会看到一堆删除IP了
————————分割————————
我直接把IPPool的getIP方法的最后一段
return ip
改成了
return ip[0:2]
这样外面的ip队列获取到的ip就仍然是[ip,端口]的模式，然后从IPProxyPool中获取IP的那两句我把空格删掉了，理论上应该就能运行了。
或者把你的format_proxy加到getIP里面，把return值改成format_proxy，这样也可以保证ip队列的正常运行（requests的代理参数的格式很多）
至于为什么是理论上，因我的IPProxyPool项目不知为毛打不开了，连不上数据库，但是我用命令行能连上，查了一下是端口的问题，暂时懒得排查了
但是这种改法没有很好的利用IPProxyPool项目新加的评分系统，有那个评分系统的话，我代码中有很多针对代理的反复测试部分就是废代码了，不过我现在也懒得改，因为我现在正在准备考研中，没啥时间
你要不要考虑fork个一个分支改完了请求合并？和我一样嫌麻烦的话，改一下getIP函数和从IPProxyPool中获取IP的那两个空格就行了，现在实在是没有时间去看

**Comment by shuiqukeyou** [comment]
你要是改了getIP函数和从IPProxyPool中获取IP的那两个空格之后可以跑起来了的话这个issue就可以close了，剩下的就是反复在代理池耗尽时手动删除IPProxyPool的数据表以及手动重启IPProxyPool项目了，等我考研搞完了我还要重构一波这个项目，虽然以后大概都用不上了，但是这里面的代码写的简直丢人

**Comment by BLMYX01** [comment]
感谢大大用心回答orz，受教了！作为学习的话个人特别喜欢这个项目，我这就去改一改。考研加油！
--------------------------------------------------------------------------------------------------------------
现在应该是解决了处理代理出错的问题，不过似乎又遇到了网站那边反爬的阻碍？
循环出现”代理通过测试”，“API爬虫的代理已被Ban，更换代理”，以及不断爬回Cloudflare的页面
![default](https://user-images.githubusercontent.com/19875394/31313287-22db1c8a-ac11-11e7-827f-9ba16ac5ec36.png)
我自己去研究一下，咸鱼大大()好好准备考研hhh

**Comment by BLMYX01** [comment]
感谢大大用心回答orz，受教了！作为学习的话个人特别喜欢这个项目，我这就去改一改。考研加油！
现在应该是解决了处理代理出错的问题，不过似乎又遇到了新的（反爬?）阻碍......
 循环出现”代理通过测试”，“API爬虫的代理已被Ban，更换代理”，以及不断爬回Cloudflare的页面
![default](https://user-images.githubusercontent.com/19875394/31313328-a3db858a-ac12-11e7-8968-e994a4fbecb7.png)
emmm...单独把你的findPage(lastpage, lastgid, lasttoken, proxy)函数提取出来运行是能够正常爬取画廊内容的，似乎是indexgeter(qi)哪里出了问题。
顺带，getIP()函数中try块中的delIP()好像有点问题，会把通过测试的代理也给删了
我再自己去研究一下，咸鱼大大()好好准备考研hhh

**Comment by BLMYX01** [comment]
cookies....应该是没有问题的（在正常访问https://exhentai.org/的前提下从谷歌浏览器的"Cookie"中获得）
![2](https://user-images.githubusercontent.com/19875394/31313565-488ee850-ac19-11e7-980c-7912d586afcc.png)
既然单独用findPage()能正常获取页面内容，一大堆爬虫进程去获取就出错，应该是网站设了什么验证码吧

**Comment by shuiqukeyou** [comment]
这大概是EH的新反爬，年初的时候是没有的，Cloudflare是美国的一个服务器提供商，EH可能是把服务器迁移到这上面了，或者以前就是（我记得以前服务器在欧洲来着），但是没用这家公司的反机器人业务。

当初更换代理的设定是，页面解析失败有三种情况：熊猫、EH的“your IP balabala”（banIP）、代理本身的错误页面，如果是后两种就会执行更换IP，但现在加的这个新型验证也会使得当前IP被认为是废IP，然后触发更换代理

只是验证码倒是好说，图片、滑动、拼图之类的都好解决（汉字验证码国外不存在的，谷歌的“我不是机器人”非常难搞，个人能搞掉那个验证码可以直接进一线互联网公司），网上大把现成教程，我搞过图片的和滑动的，但是这类大公司的反爬大概都是基于机器学习的，单纯的换代理还是会很快的被识别出来

但如果不是基于机器学习的话，就是因为同一个cookie反复更换IP导致的，准备一大堆帐号可破，但是整个程序需要大改（其实也不行，单个IP大概单日5000~7000个页面访问量就ban了，之后仍然会触发验证码）

反正验证码本身都不是问题（机器学习流和“我不是机器人”论外），问题是为什么会触发验证码，这里是个深坑，基本就是和EH的反爬工程师斗智斗勇，你要是很闲的话可以搞搞，确实能学一堆东西

——————分割——————
删通过测试的IP是我故意设计的，因为你要是翻getIP的底层方法的话，是默认返回IPProxyPool项目返回的第一个代理的，如果不删除的话会导致后面的getIP重复拿到这一个IP，IPProxyPool不提供IP回写功能非常的日狗，有一个类似的项目，也是国人写的，就有回写功能，不过是我做完这个之后发现的了

**Comment by BLMYX01** [comment]
好的，多谢前辈指教了orz！不厌其烦地帮我解答了各种问题，收获很大，感谢！
我再仔细研究一下你的项目。前辈大大考研加油！
