### ISSUE TITLE
关于 new_datatable.py 的一点小问题

### ISSUE THREAD

**Issue by VergeDX** [shuiqukeyou/E-HentaiCrawler#3]
在 `E-HentaiCrawler/database/newdatabase` 目录中，执行 `python3.6 new_datatable.py ` 后报错如下：

`````python
Traceback (most recent call last):
  File "new_datatable.py", line 2, in <module>
    from database.link_database import link_database
ModuleNotFoundError: No module named 'database'
`````

小白求教...

**Comment by VergeDX** [comment]
数据库链接好之后又出现了新的问题...
![2018-09-30_211641](https://user-images.githubusercontent.com/25173827/46257996-24036000-c4f6-11e8-82cb-1da215980c40.png)
然后就不动了...不管挂不挂代理都是这样...

**Comment by VergeDX** [comment]
差不多明白了…

**Comment by shuiqukeyou** [comment]
抱歉，在准备考研，完全没空看github

2018年10月1日 08:33，"Vanilla" <notifications@github.com>写道：

**Comment by VergeDX** [comment]
没事没事，您考研加油
窝差不多明白这个怎么用了
窝当时因为IP地址池没有俄罗斯代理所以报错了
现在已经明白了，谢谢！
