### ISSUE TITLE
我最近也在写绅士爬虫，问一下关于cookie 的问题

### ISSUE THREAD

**Issue by hjyssg** [shuiqukeyou/E-HentaiCrawler#4]
如果我从browser把cookie复制出来，然后爬虫发送的时候放到header就行了？

**Comment by shuiqukeyou** [comment]
我当时模拟自动登录发现cookie少字段，就用了复制cookie的办法，我是从浏览器插件里复制cookie的，而不是浏览器本身。
因为当时登录e绅士有一些所谓的教程（比如这个：https://mapgun.com/archives/1544
）会教人用浏览器插件看cookie然后一通操作，而我当时也是参照的这类教程上了e绅士的车的。
所以准确的来讲我是从插件里面复制的而不是浏览器本身，但是按照我现在的认识水平来看，我觉得从浏览器里复制也行。
不过更好的解决办法是把e绅士的登录流程摸清楚了，使得自动登录不会少字段，因为E绅士现在除了限制IP访问频率，还限制帐号访问频率（不是图片配额问题），所以我的这个项目已经没用了，因为做的时候压根没考虑需要多账号。
并且后来代码能力上去了一些之后发现里面有一些非常恶性的BUG，但是也懒得改了。
你现在要做爬虫的话就需要解决帐号池的问题，要解决帐号池就得把模拟登录吃下来（应该不难，毕竟有ehviewer这种好用的第三方客户端存在），所以不建议你用复制cookie的办法做登录。

hjy <notifications@github.com> 于2019年2月20日周三 上午10:23写道：

**Comment by hjyssg** [comment]
好，谢谢我去问ehviewer的作者。
你知道他们这个限制访问频率是多少吗？
我只是想爬一万多本同人的tag信息。

**Comment by hjyssg** [comment]
或许你知道哪里有同人数据库？没有cookie限制的。

**Comment by shuiqukeyou** [comment]
e绅士表站不需要登录帐号就能看，所以如果是我的话我应该会考虑表站拿大部分数据，剩下的在EX站拿，需要的账号数能少很多。
同人数据库我记得有不少（不过我一个都记不住了），但是各有偏向，比如我记得有个直接记录comic历届本子数据的网址，似乎是comic官方的，但是只有作者名字、社团名字、原作（就是到底是哪个作品的本子，还是原创本）这种，什么tag、销量、评分这些显然就没有记录，要看你的需求，另外你还需要一个技术更高超的司机。
访问频率我当时记得体感不是一个固定数字，如果程序不设延迟一秒爬爆的话十几秒就没了，几秒爬一个大概几千个才封，不知道现在改了没。
